services:
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    environment:
      - TZ=Asia/Shanghai
    network_mode: "host"
    volumes:
      - ../persistence/ddns-go/:/root
    restart: unless-stopped