services:
  web:
    image: nginx
    container_name: nginx
    volumes:
     - ./templates/:/etc/nginx/templates/
     - ./ssl/:/etc/nginx/ssl/
     - ./log/:/var/log/nginx/
     - ./blog/:/var/www/blog/
     - ./word-spelling/:/var/www/word-spelling/
     - ./download/:/var/www/download/
     - ./nginx.conf/:/etc/nginx/nginx.conf/
    ports:
     - "80:80"
     - "443:443"
    environment:
     - NGINX_HOST=newthread.run
     - NGINX_PORT=443 ssl
    restart: unless-stopped