services:
  web:
    image: nginx
    container_name: nginx
    volumes:
     - /etc/timezone:/etc/timezone:ro
     - /etc/localtime:/etc/localtime:ro
     - ./templates/:/etc/nginx/templates/
     - ./ssl/:/etc/nginx/ssl/
     - ./logs/:/var/logs/nginx/
     - ./blog/:/var/www/blog/
     - ./word-spelling/:/var/www/word-spelling/
     - ./download/:/var/www/download/
     - ./nginx.conf/:/etc/nginx/nginx.conf/
     - ./nginx_cache/:/cache/
    ports:
     - "80:80"
     - "443:443"
    environment:
     - SSL_CONFIG=/etc/nginx/conf.d/ssl-config
     - NGINX_HOST=hevc.cc
     - NGINX_PORT=443 ssl
     - SSL_CERT=ssl_certificate /etc/nginx/ssl/cloudflare-hevc.cc.pem
     - SSL_KEY=ssl_certificate_key /etc/nginx/ssl/cloudflare-hevc.cc.key
    restart: on-failure:5