services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./templates/:/etc/nginx/templates/
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../persistence/nginx/ssl/:/etc/nginx/ssl/
      - ../persistence/nginx/logs/:/var/log/nginx/
      - ../persistence/nginx/blog/:/var/www/blog/
      - ../persistence/nginx/word-spelling/:/var/www/word-spelling/
      - ../persistence/nginx/download/:/var/www/download/
      - ../persistence/nginx/cache/:/cache/
    ports:
      - "80:80"
      - "443:443"
      - "880:880"
      - "4443:4443"
    network_mode: bridge
    environment:
      - SSL_CONFIG=/etc/nginx/conf.d/ssl-config
      - NGINX_HOST=hevc.cc
      - NGINX_PORT=443 ssl
      - SSL_CERT=ssl_certificate /etc/nginx/ssl/hevc.cc.pem
      - SSL_KEY=ssl_certificate_key /etc/nginx/ssl/hevc.cc.key
    restart: unless-stopped