---
services:
  transmission:
    image: woahbase/alpine-transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - USER= admin
      - PASS= 0shimima
      - TORRENT_PORT_HTTP=9091
      - TORRENT_PORT_NAT=22789
      - USERNAME=admin
      - PASSWORD=0shimima
    volumes:
      - ./config:/var/lib/transmission/config
      - /mnt/usb1/downloads:/var/lib/transmission/downloads
      - ./watch:/var/lib/transmission/torrents
    ports:
      - 9091:9091
      - 22789:22789
      - 22789:22789/udp
    network_mode: host
    restart: unless-stopped
